model:
  params:
    colsample_bytree: 0.949925017002092
    eval_metric: logloss
    learning_rate: 0.16432307216478526
    max_depth: 5
    min_child_weight: 3
    n_estimators: 162
    objective: binary:logistic
    random_state: 42
    reg_alpha: 0.0001253985842292896
    reg_lambda: 4.79762558469835e-06
    subsample: 0.6017638901556924
